version: '3.8'

services:
  render-engine:
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY:-secret-key-change-me}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET=renders
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
